version: '3'

services:
  web:
    image: 'nginx:alpine'
    volumes:
      - ./src:/app
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '83:80'
  php-fpm:
    image: 'php:7.3-fpm-alpine'
    volumes:
      - ./src:/app
